name: Tests

on:
    # Trigger analysis when pushing in master or pull requests, and when creating
    # a pull request.
    push:
        branches:
            - master
    pull_request:
        types: [ opened, synchronize, reopened ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
                with:
                    # Disabling shallow clone is recommended for improving relevancy of reporting
                    fetch-depth: 0

            -   name: Install dependencies
                run: make setup

            -   name: Run Tests
                run: make test

            -   name: SonarCloud Scan
                uses: sonarsource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
